# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/MEVHorizontalContacts.xcworkspace -scheme MEVHorizontalContacts-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint

language: objective-c  #1
osx_image: xcode7.2 #2
xcode_workspace: Example/MEVFloatingButton.xcworkspace #3
xcode_scheme: MEVFloatingButton-Example #4
xcode_sdk: iphonesimulator9.2 #5
